---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: instavote-deploy
    kustomize.toolkit.fluxcd.io/namespace: instavote
  name: instavote-deploy
  namespace: instavote
spec:
  gitImplementation: go-git
  interval: 1h
  ref:
    branch: main
  timeout: 20s
  url: https://github.com/dahston/instavote-deploy.git
  secretRef:
    name: github-instavote
