---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: worker-staging
  namespace: instavote
spec:
  dependsOn:
  - name: redis-staging
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1h
  path: ./kustomize/
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  targetNamespace: instavote
  timeout: 2m0s

