apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 4
images:
- name: dahston/vote
  newTag: main-a81f6aa0-1666732236 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "danieldwan@gmail.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
